# Created by Daniel Stevanus
# jogjezz@gmail.com

networks:
  magez:
    external: true  


services:
  mage:
    image: mageai/mageai:latest
    container_name: magic
    depends_on:
      - postgres
    command: mage start magic
    environment:
      ENV: dev
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      PG_HOST_PORT: 35432
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    networks: [ magez ]
    

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    container_name: postgres-db
    hostname: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 35432:5432
    networks: [ magez ]

    
